### ISSUE TITLE
Please migrate to Todoist REST API v2

### ISSUE THREAD

**Issue by Schnouki** [SmBe19/ThunderbirdTodoist#16]
Hey there,

I'm a software engineer at Doist, working on the Todoist backend 👋

I just discovered this add-on, and while quickly reviewing it before installing it on my laptop, I discovered that it's using the Todoist REST API v1. So, I just wanted to warn you (in case you didn't notice already) that the v1 API will be deprecated soon (Nov 30, 2022), so you should migrate to the REST API v2 by then. The differences between those API versions are described in the [migration guide](https://developer.todoist.com/rest/v2/#migrating-from-v1). From what I can tell, it should be pretty straightforward for the use cases covered by this add-on: basically, change `project_id` to be a string, and that should be it 🙂 (Existing integer `project_id`s can be safely converted to strings.)

And, one last thing: thanks for this nice add-on! 😊

**Comment by SmBe19** [comment]
Hey,

Thank you so much for letting me know. I was not aware that the v1 API will be deprecated. I have updated the addon and the update should be available on the addon store soon.
