### ISSUE TITLE
Is it planed to send attachements to todoist?

### ISSUE THREAD

**Issue by MAWSpitau** [SmBe19/ThunderbirdTodoist#17]
Hi there, 

what a great Plugin! Is it somewhen planned to have mail-attachemnts sent to todoist?

Greetings
Marcel

**Comment by SmBe19** [comment]
Hi,

It is currently not planned to implement sending mail-attachments to Todoist. As far as I can see, the Todoist REST API does only support sending attachments if they are hosted externally. To upload directly to Todoist I would need to switch to the Sync API, which is much more complicated. Hosting externally is not an option, so I don't plan to implement this currently.
