### ISSUE TITLE
Empty widget on add task

### ISSUE THREAD

**Issue by datainlife** [SmBe19/ThunderbirdTodoist#18]
Hi!

Thank you for plugin. I love Thunderbird, but integration with Todoist was absent for a long time.

Plugin works on first time, when run Thunderbird on Macos.

But if I try to add task for another message at the same Thunderbird run session, plugin snows empty widget square
<img width="485" alt="2023-02-02_18-04-09" src="https://user-images.githubusercontent.com/42066746/216361587-466f303e-0d79-444e-afc6-694e8b636bc5.png">

Only reload application allow me to add task only one time, and reload again, ...

**Comment by SmBe19** [comment]
I can not reproduce this. Are you still seeing this issue with version 0.6 of the extension?
