### ISSUE TITLE
Compatibility with Thunderbird 115

### ISSUE THREAD

**Issue by gpuccio87** [SmBe19/ThunderbirdTodoist#19]
Hello. And thank you for your work. Is it possible to update the extension to be compatible with Thunderbird 115? I really use this extension a lot, and I would be sorry not to be able to use it anymore. Thank you

**Comment by SmBe19** [comment]
As the interface of Thunderbird changed quite a bit in 115 I will first need to test the extension with the new release. As I am currently quite busy this might take a few weeks.

In the meantime, you can adjust the extension to work with 115 and test whether everything works:
1. Change the `strict_max_version` in [manifest.json](https://github.com/SmBe19/ThunderbirdTodoist/blob/master/thunderbird-todoist/manifest.json) to `115`.
2. Change the `version` in [manifest.json](https://github.com/SmBe19/ThunderbirdTodoist/blob/master/thunderbird-todoist/manifest.json) to `0.5.1`.
3. Run the [release script](https://github.com/SmBe19/ThunderbirdTodoist/blob/master/release.py).
4. This creates a `.xpi` file which you can [install in Thunderbird](https://support.mozilla.org/en-US/kb/installing-addon-thunderbird).

Please let me know if you face any issues in Thunderbird 115.

Once I was able to test the extension I will update the official version to work with 115.

**Comment by SmBe19** [comment]
I had some time just now to test this. There were a few fixes required and if you are using mail-links you will need to adjust the protocol registration.

The new version which is compatible with Thunderbird 115 should be available on the official addons page in a few days.

**Comment by gpuccio87** [comment]
Thank you!
