### ISSUE TITLE
Add direct link to email

### ISSUE THREAD

**Issue by SorinaW** [SmBe19/ThunderbirdTodoist#3]
Hi, 
so I am not really familiar with how the issues work, I just have a general question. 

I installed the Add-on and tested with to-do ist and it works. Yey, thanks for that! What it now does now is it creates a task in Todoist that contains only the title of the email, without a link back to the email. Is this all that the add-on is supposed to do at this stage? 

I am asking because I have seen a tutorial and the integration with Spark lets you set a reminder but also has a link back to the email, which makes sense because then we don`t have to do the email search again and we tackle the email right away. 

I guess my question is whether the link back to the email is possible to implement or am I just doing something wrong?? 

Thanks, 
Sorina 
![Screenshot_28](https://user-images.githubusercontent.com/31551788/106609643-15b22c80-6566-11eb-8c1e-43c31209ad6e.jpg)

**Comment by SmBe19** [comment]
Hi,
Currently it's not yet possible to have links back to the email. There is currently PR #2 which implements such a feature, but it's not quite ready. So hopefully adding a link will be possible soon, but currently this add-on is only capable of adding the title of the email.
Cheers
