### ISSUE TITLE
Add an option to include the body of the email as a comment

### ISSUE THREAD

**Issue by gdesmott** [SmBe19/ThunderbirdTodoist#6]
Thanks for this nice extension!

It would be great to have en option allowing to automatically embed the body of the email as a task comment.

**Comment by oppermannkalipzo** [comment]
I would appreciate this, too!

**Comment by bepolymathe** [comment]
Me too !

**Comment by Marlon154** [comment]
@SmBe19 I could do it. Are you still working on this project?

**Comment by SmBe19** [comment]
@Marlon154 Yes, I am still maintaining the project, but I just did not have a lot of time to work on this the last few months. If you implement this and create a PR I am happy to review it and merge it.

**Comment by SmBe19** [comment]
This was now implemented in 371dab1a70b9a65b05c98229fc5837c7816c34c6. I will wait with an official release until I get some more issues resolved, but I'll publish a snapshot release shortly.
