### ISSUE TITLE
Button to add task from message itself

### ISSUE THREAD

**Issue by mhalano** [SmBe19/ThunderbirdTodoist#7]
I just was able to see the button to add a task from compose screen. It would be nice to have in the message itself a button to add a task. I think I read a message and I need to do something about (check something, get something, etc.) so I don't think I would need to open compose screen (like to reply that message) to get the button and add the task.
![image](https://user-images.githubusercontent.com/6025031/123562741-02a72f80-d787-11eb-8746-6048826e601a.png)

**Comment by SmBe19** [comment]
For me, the 'Add Task' button also appears in the message read pane.

![Bildschirmfoto von 2021-09-15 18-04-33](https://user-images.githubusercontent.com/6072509/133468965-6060f065-2251-416f-bf66-4d2b39290047.png)
